{% set name = "approvaltests" %}
{% set version = "15.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/approvaltests-{{ version }}.tar.gz
  sha256: c8865293d90b67ed118c17b40478d2a869e22f8f1a8a2bca9efe6a3687853cdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest >=4.0.0
    - empty-files >=0.0.3
    - typing-extensions >=3.6.2
    - pyperclip >=1.5.29
    - beautifulsoup4 >=4.4.0
    - allpairspy >=2.1.0
    - testfixtures >=7.1.0
    - mock >=5.1.0
    - approval-utilities =={{ version }}

test:
  imports:
    - approvaltests
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/approvals/ApprovalTests.Python
  summary: Assertion/verification library to aid testing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
