{% set name = "approvaltests" %}
{% set version = "14.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/approvaltests-{{ version }}.tar.gz
  sha256: 47c2d90a78de720764da33fe2cb9bbf680e7d0607cebfbd3dae3c9b0085b3031

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytest >=4.0.0
    - empty-files >=0.0.3
    - typing-extensions >=3.6.2
    - pyperclip >=1.5.29
    - beautifulsoup4 >=4.4.0
    - allpairspy >=2.1.0
    - mrjob >=0.7.4
    - testfixtures >=7.1.0
    - mock >=5.1.0
    - approval-utilities =={{ version }}

test:
  imports:
    - approvaltests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/approvals/ApprovalTests.Python
  summary: Assertion/verification library to aid testing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
