schema_version: 1

context:
  version: "19.1.1"
  ignore_tests:
    # missing files
    - " --ignore tests/test_ai_fixer_loop.py"
    # breaks pytest due to importing setup.py
    - "--ignore tests/test_workflow_matrix.py"

recipe:
  name: approvaltests
  version: ${{ version }}

source:
  url: https://github.com/approvals/ApprovalTests.Python/archive/v${{ version }}.tar.gz
  sha256: ac351d3e0fd2f2e7ecf7a1d2be33d56424f07e4c4699c2fa2735c0a7a8120d35

build:
  number: 1
  noarch: python

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/approvals/ApprovalTests.Python

outputs:
  - package:
      name: approval-utilities

    build:
      script:
        - cp setup/setup.approval_utilities.py setup.py
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python ${{ python_min }}.*
        - setuptools >=69.0.0
        - wheel
        - pip
      run:
        - python >=${{ python_min }}
        - typing_extensions >=4.12.0

    tests:
      - python:
          imports:
            - approval_utilities
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"

    about:
      summary: Utilities for your production code that work well with approvaltests

  - package:
      name: approvaltests

    build:
      script:
        - cp setup/setup.approvaltests.py setup.py
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
      run:
        - python >=${{ python_min }}
        # requirements.prod.required.txt
        - pytest >=8.0.0
        - empty-files >=0.0.3
        - typing_extensions >=4.12.0
        # requirements.prod.extras.txt
        - pyperclip >=1.5.29
        - beautifulsoup4 >=4.9.0
        - allpairspy >=2.1.0
        - testfixtures >=7.1.0,<12
        - mock >=5.1.0
        - psutil >=5.9.0
        - approval-utilities ==${{ version }}

    tests:
      - python:
          imports:
            - approvaltests
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"
      - script:
          - TZ=UTC python -m pytest ${{ ignore_tests | join(' ') }}
        requirements:
          run:
            - pytest-asyncio
            - python ${{ python_min }}.*
            - numpy
            - pyyaml
        files:
          source:
            - approval_utilities/
            - approvaltests/
            - tests/

    about:
      summary: Assertion/verification library to aid testing

extra:
  recipe-maintainers:
    - apmorton
    - mgorny
