schema_version: 1

context:
  name: approvaltests
  version: "19.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/approvaltests-${{ version }}.tar.gz
  sha256: 4ea52ba0db11825fb380a146f56b2d1af380ad979bce5f00759997d13285132d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pytest >=4.0.0
    - empty-files >=0.0.3
    - typing-extensions >=3.6.2
    - pyperclip >=1.5.29
    - beautifulsoup4 >=4.4.0
    - allpairspy >=2.1.0
    - testfixtures >=7.1.0
    - mock >=5.1.0
    - approval-utilities ==${{ version }}

tests:
  - python:
      imports:
        - approvaltests
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Assertion/verification library to aid testing
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/approvals/ApprovalTests.Python

extra:
  recipe-maintainers:
    - apmorton
